### ISSUE TITLE
issue in installing

### ISSUE THREAD

**Issue by hyusetiawan** [primal100/django_nosql#2]
for Python 3.4.3:

pip install django-postgres-extensions
Collecting django-postgres-extensions
  Using cached django_postgres_extensions-0.91.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/pf/rd6y8q8x5yldbz4m1mb7xdyr0000gn/T/pip-build-r9fif_w7/django-postgres-extensions/setup.py", line 8, in <module>
        long_description=open('readme.md').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'readme.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/pf/rd6y8q8x5yldbz4m1mb7xdyr0000gn/T/pip-build-r9fif_w7/django-postgres-extensions/

**Comment by primal100** [comment]
Hey, 

I've fixed this up and a few other issues with release 0.9.2.  I've tested the install on Python 2 and Python 3.

Cheers
